name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - refactor-structure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install esbuild
        run: npm install esbuild

      # --- BUILD DE PRODUÇÃO (Apenas na main) ---
      - name: Build Production (bundle.js)
        if: github.ref == 'refs/heads/main'
        run: ./node_modules/.bin/esbuild src/app.js --bundle --outfile=dist/bundle.js --minify

      # --- BUILD DE DESENVOLVIMENTO (Apenas na refactor) ---
      # Cria um arquivo com nome diferente: bundle-dev.js
      - name: Build Development (bundle-dev.js)
        if: github.ref == 'refs/heads/refactor-structure'
        run: ./node_modules/.bin/esbuild src/app.js --bundle --outfile=dist/bundle-dev.js --minify
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: ''
          # IMPORTANTE: Isso impede que o deploy da refactor apague o arquivo da main e vice-versa
          keep_files: true